// <auto-generated />
using System;
using Earth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Earth.Migrations
{
    [DbContext(typeof(EarthContext))]
    [Migration("20260201040837_UpdateExploreSeedData")]
    partial class UpdateExploreSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Earth.Models.AboutContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AboutContents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "/images/earth.jpg",
                            Introduction = "HelloEarth is an educational website that helps users explore and understand our planet.",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mission = "To educate and inspire people to learn about Earth's systems, environments, and life.",
                            Vision = "A future where everyone understands and cares for our planet."
                        });
                });

            modelBuilder.Entity("Earth.Models.EarthModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explaination")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ID");

                    b.ToTable("EarthModel");
                });

            modelBuilder.Entity("Earth.Models.ExploreTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KeyFacts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ExploreTopics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullContent = "Biodiversity encompasses the diversity of life at all levels, from genetic variation within species to entire ecosystems. Healthy biodiversity ensures that ecosystems can withstand environmental changes, provide food, regulate climate, and support natural cycles such as pollination and nutrient recycling.\nHuman activities such as deforestation, pollution, and climate change are major threats to biodiversity. Protecting biodiversity through conservation, sustainable resource use, and environmental awareness is critical to maintaining the balance of life on Earth and ensuring future generations can thrive.",
                            ImagePath = "/images/bio.jpg",
                            KeyFacts = "• Earth has 8.7 million species\n• Rainforests contain 50% of world's species\n• 1 million species face extinction",
                            ShortDescription = "Biodiversity refers to the variety of living organisms on Earth, including plants, animals, and microorganisms. It is essential for ecosystem stability and human survival.",
                            Title = "Biodiversity"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullContent = "Climate influences where plants and animals can survive and how ecosystems function. Earth’s climate system is driven by interactions between the atmosphere, oceans, land surfaces, and ice, creating regional and global climate patterns over time.\nIn recent decades, human activities such as burning fossil fuels and deforestation have accelerated climate change. Rising global temperatures, melting ice caps, and extreme weather events highlight the importance of understanding climate systems and taking action to reduce environmental impact.",
                            ImagePath = "/images/climate.jpg",
                            KeyFacts = "• Global temperature rose 1.1°C since 1880\n• CO2 levels are highest in 3 million years\n• Sea levels rising 3.3 mm per year",
                            ShortDescription = "Climate describes the long-term patterns of temperature, precipitation, and weather conditions on Earth. It plays a major role in shaping ecosystems and human societies.",
                            Title = "Climate"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullContent = "Oceans play a crucial role in controlling Earth’s temperature by absorbing heat and carbon dioxide from the atmosphere. They also drive weather patterns and support global food systems through fisheries and marine ecosystems.\nDespite their importance, oceans face serious threats such as pollution, overfishing, and climate change. Protecting marine environments through sustainable practices and conservation efforts is essential for preserving ocean health and maintaining Earth’s ecological balance.",
                            ImagePath = "/images/oceans.jpg",
                            KeyFacts = "• Oceans cover 71% of Earth\n• Average depth is 3,688 meters\n• Oceans produce 50-80% of Earth's oxygen",
                            ShortDescription = "Oceans cover more than 70% of Earth’s surface and are vital to life on the planet. They regulate climate and support a vast range of marine life.",
                            Title = "Oceans"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullContent = "Earth’s continents were formed through tectonic plate movements over millions of years. These landmasses contain mountains, deserts, forests, and rivers that support diverse forms of life and natural resources essential to human civilization.\nContinents influence climate patterns by affecting ocean currents and atmospheric circulation. Understanding continental geography helps us better appreciate Earth’s natural processes and the interconnectedness between land, climate, and living organisms.",
                            ImagePath = "/images/continents.jpg",
                            KeyFacts = "• Asia is the largest continent\n• Africa is the 'cradle of humankind'\n• Antarctica holds 90% of world's ice",
                            ShortDescription = "Continents are large landmasses that shape Earth’s geography and influence climate, biodiversity, and human development. Each continent has unique landscapes and ecosystems.",
                            Title = "Continents"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
