// <auto-generated />
using System;
using Earth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Earth.Migrations
{
    [DbContext(typeof(EarthContext))]
    [Migration("20260131185754_AddExploreTopic")]
    partial class AddExploreTopic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Earth.Models.AboutContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AboutContents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "/images/earth.jpg",
                            Introduction = "HelloEarth is an educational website that helps users explore and understand our planet.",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mission = "To educate and inspire people to learn about Earth's systems, environments, and life.",
                            Vision = "A future where everyone understands and cares for our planet."
                        });
                });

            modelBuilder.Entity("Earth.Models.EarthModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explaination")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ID");

                    b.ToTable("EarthModel");
                });

            modelBuilder.Entity("Earth.Models.ExploreTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KeyFacts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ExploreTopics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullContent = "Biodiversity refers to the variety of life on Earth. It includes different plants, animals, and microorganisms, as well as the ecosystems they form.",
                            ImagePath = "/images/bio.jpg",
                            KeyFacts = "• Earth has 8.7 million species\n• Rainforests contain 50% of world's species\n• 1 million species face extinction",
                            ShortDescription = "Discover the incredible variety of life on Earth.",
                            Title = "Biodiversity"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullContent = "Climate is the long-term pattern of weather in a particular area. Earth's climate is influenced by the atmosphere, oceans, and land.",
                            ImagePath = "/images/climate.jpg",
                            KeyFacts = "• Global temperature rose 1.1°C since 1880\n• CO2 levels are highest in 3 million years\n• Sea levels rising 3.3 mm per year",
                            ShortDescription = "Learn about Earth's climate systems and weather patterns.",
                            Title = "Climate"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullContent = "Oceans are large bodies of salt water that cover most of Earth's surface. They regulate climate and support marine life.",
                            ImagePath = "/images/oceans.jpg",
                            KeyFacts = "• Oceans cover 71% of Earth\n• Average depth is 3,688 meters\n• Oceans produce 50-80% of Earth's oxygen",
                            ShortDescription = "Explore the vast oceans covering 71% of Earth's surface.",
                            Title = "Oceans"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullContent = "Continents are large land masses on Earth. There are seven continents: Asia, Africa, North America, South America, Antarctica, Europe, and Australia.",
                            ImagePath = "/images/continents.jpg",
                            KeyFacts = "• Asia is the largest continent\n• Africa is the 'cradle of humankind'\n• Antarctica holds 90% of world's ice",
                            ShortDescription = "Discover Earth's seven continents and their features.",
                            Title = "Continents"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
