// <auto-generated />
using System;
using Earth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Earth.Migrations
{
    [DbContext(typeof(EarthContext))]
    [Migration("20260201052149_UpdateExploreSeedData2")]
    partial class UpdateExploreSeedData2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Earth.Models.AboutContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AboutContents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "/images/earth.jpg",
                            Introduction = "HelloEarth is an educational website that helps users explore and understand our planet.",
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mission = "To educate and inspire people to learn about Earth's systems, environments, and life.",
                            Vision = "A future where everyone understands and cares for our planet."
                        });
                });

            modelBuilder.Entity("Earth.Models.EarthModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explaination")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ID");

                    b.ToTable("EarthModel");
                });

            modelBuilder.Entity("Earth.Models.ExploreTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KeyFacts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ExploreTopics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullContent = "Biodiversity operates at multiple interconnected levels, encompassing genetic variation within populations, differences among species, and the complexity of ecosystems across terrestrial, freshwater, and marine environments. High levels of biodiversity contribute to ecosystem resilience by enabling natural systems to recover from disturbances such as climate variability, natural disasters, and disease outbreaks, while also maintaining essential ecological processes like nutrient cycling, soil formation, water filtration, and pollination.\nThe survival and development of human societies are deeply dependent on biodiversity, as it provides food sources, medicinal compounds, raw materials, and cultural value; however, modern human activities have dramatically accelerated biodiversity loss. Habitat fragmentation, deforestation, pollution, invasive species, and climate change have led to declining populations and increased extinction rates, making biodiversity conservation a global priority to preserve ecosystem services and maintain environmental balance for future generations.",
                            ImagePath = "/images/bio.jpg",
                            KeyFacts = "• Earth has 8.7 million species\n• Rainforests contain 50% of world's species\n• 1 million species face extinction",
                            ShortDescription = "Biodiversity refers to the variety of living organisms on Earth, including plants, animals, and microorganisms. It is essential for ecosystem stability and human survival.",
                            Title = "Biodiversity"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullContent = "Earth’s climate system is governed by the interaction of several components, including the atmosphere, hydrosphere, cryosphere, lithosphere, and biosphere, which together regulate the distribution of energy received from the Sun. Processes such as the greenhouse effect, ocean circulation, and atmospheric dynamics play critical roles in maintaining temperature balance and shaping regional climate zones, ranging from polar regions to tropical rainforests.\nIn recent centuries, human-induced climate change has become a dominant force affecting the global climate system, primarily due to increased greenhouse gas emissions from industrialization, transportation, and land-use changes. These changes have resulted in rising global temperatures, altered precipitation patterns, increased frequency of extreme weather events, and disruptions to ecosystems, highlighting the urgent need for climate science, mitigation strategies, and sustainable environmental policies.",
                            ImagePath = "/images/climate.jpg",
                            KeyFacts = "• Global temperature rose 1.1°C since 1880\n• CO2 levels are highest in 3 million years\n• Sea levels rising 3.3 mm per year",
                            ShortDescription = "Climate describes the long-term patterns of temperature, precipitation, and weather conditions on Earth. It plays a major role in shaping ecosystems and human societies.",
                            Title = "Climate"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullContent = "Oceans function as a major component of Earth’s climate system by absorbing solar radiation and redistributing heat through global ocean currents, which influence atmospheric circulation and regional weather patterns. They also act as a significant carbon sink, absorbing large amounts of carbon dioxide from the atmosphere, thereby helping to regulate global climate and slow the pace of climate change.\nBeyond climate regulation, oceans support an extraordinary diversity of life, ranging from microscopic plankton to large marine mammals, forming complex food webs that sustain both marine and terrestrial ecosystems. However, ocean health is increasingly threatened by human activities such as pollution, plastic waste accumulation, overfishing, coral reef destruction, and ocean acidification, underscoring the importance of marine conservation and sustainable ocean management practices.",
                            ImagePath = "/images/oceans.jpg",
                            KeyFacts = "• Oceans cover 71% of Earth\n• Average depth is 3,688 meters\n• Oceans produce 50-80% of Earth's oxygen",
                            ShortDescription = "Oceans cover more than 70% of Earth’s surface and are vital to life on the planet. They regulate climate and support a vast range of marine life.",
                            Title = "Oceans"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullContent = "The continents of Earth were formed through tectonic plate movements driven by processes within the planet’s mantle, resulting in the gradual shifting, collision, and separation of landmasses over geological time. These processes have produced major geological features such as mountain ranges, volcanic regions, plains, and sedimentary basins, all of which influence regional ecosystems and biodiversity patterns.\nContinents play a critical role in shaping global climate systems by influencing ocean currents, wind patterns, and precipitation distribution, which directly affect the development of ecosystems and human settlements. Understanding continental structure and dynamics is essential for studying Earth’s geological history, natural resource distribution, and the complex relationship between physical geography and environmental sustainability.",
                            ImagePath = "/images/continents.jpg",
                            KeyFacts = "• Asia is the largest continent\n• Africa is the 'cradle of humankind'\n• Antarctica holds 90% of world's ice",
                            ShortDescription = "Continents are large landmasses that shape Earth’s geography and influence climate, biodiversity, and human development. Each continent has unique landscapes and ecosystems.",
                            Title = "Continents"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
